name: CI/CD 
on:
  push:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.18'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python -m pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Set up gcloud CLI
      uses: google-github-actions/auth@v1
      with:
        project_id: ${{ secrets.PROJECT_ID }}
        credentials_json: ${{ secrets.CREDENTIALS_JSON }}
        service_account_key: ${{ secrets.SERVICE_ACCOUNT }}
        export_default_credentials: true

    - name: Build and push container image
      env:
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev
        docker build -t us-central1-docker.pkg.dev/${PROJECT_ID}/fastapi/all_ml_api_image:latest .
        docker push us-central1-docker.pkg.dev/${PROJECT_ID}/fastapi/all_ml_api_image:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy fastapi \
          --image=us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/fastapi/all_ml_api_image:latest \
          --allow-unauthenticated \
          --port=8000 \
          --service-account=${{ secrets.SERVICE_ACCOUNT }} \
          --max-instances=10 \
          --region=us-central1 \
          --project=${{ secrets.PROJECT_ID }}
